theme: jekyll-theme-minimal
title: Thais's homepage
description: My name is Thais Gomes Ribeiro. I am a third-year PhD student in Pure Mathematics at the University of Birmingham, under the supervision of Professor Tyler Kelly. My CV can be found here. Contact me at <a href="https://en.wikipedia.org/wiki/Main_Page">Wikipedia</a>.
